#============================== Network device ================================
packetbeat.interfaces.device: any

#================================== Flows =====================================
packetbeat.flows:
  timeout: 30s
  period: 10s

#========================== Transaction protocols =============================
packetbeat.protocols:
  - type: http
    ports: [5050]
    send_headers: true
    send_all_headers: true
    send_request: true
    send_response: true
    include_body_for: ["application/json", "text/plain", "x-www-form-urlencoded"]
    index: ${PACKETBEAT_INDEX}-http

#========================== Elasticsearch output ===============================
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}"]
  pipeline: geoip-info
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
  index: "${PACKETBEAT_INDEX}-%{+yyyy.MM.dd}"

#============================== Dashboards =====================================
setup.dashboards:
  enabled: true

setup.template:
  name: "${PACKETBEAT_INDEX}"
  pattern: "${PACKETBEAT_INDEX}-*"

#============================== Kibana =========================================
setup.kibana:
  host: "${KIBANA_HOST}:${KIBANA_PORT}"
  username: ${KIBANA_USERNAME}
  password: ${KIBANA_PASSWORD}
